//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinZZT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinZZT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap charmap {
            get {
                object obj = ResourceManager.GetObject("charmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;winzztmap&gt;
        ///
        ///	&lt;player x=&quot;19&quot; y=&quot;12&quot; ammo=&quot;500&quot; /&gt;
        ///
        ///	&lt;elements&gt;
        ///		
        ///		&lt;!-- Win ZZT text --&gt;
        ///		&lt;text x=&quot;15&quot; y=&quot;12&quot; char=&quot;87&quot; color=&quot;DDDDDD&quot; background=&quot;000000&quot; /&gt;
        ///		&lt;text x=&quot;16&quot; y=&quot;12&quot; char=&quot;105&quot; color=&quot;DDDDDD&quot; background=&quot;000000&quot; /&gt;
        ///		&lt;text x=&quot;17&quot; y=&quot;12&quot; char=&quot;110&quot; color=&quot;DDDDDD&quot; background=&quot;000000&quot; /&gt;
        ///		&lt;text x=&quot;21&quot; y=&quot;12&quot; char=&quot;90&quot; color=&quot;FFFFFF&quot; background=&quot;330000&quot; /&gt;
        ///		&lt;text x=&quot;22&quot; y=&quot;12&quot; char=&quot;90&quot; color=&quot;FFFFFF&quot; background=&quot;003300&quot; /&gt;
        ///		&lt;text x=&quot;23&quot; y=&quot;12&quot; char=&quot;84&quot; color=&quot;FFFFFF&quot; background= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultmap {
            get {
                return ResourceManager.GetString("defaultmap", resourceCulture);
            }
        }
    }
}
